### ISSUE TITLE
[Feature]: Hopper logic enhancement

### ISSUE THREAD

**Issue by CaszGamerMD** [spnda/BlockProt#99]
### Feature description

i feel as though the hopper shouldn't have its flow restricted, but it has to have permission to interact with a container, the locks have to align.

Example:
Chest1 is on top of hopper, which feeds into Chest2

Scenario A: nothing is locked
everything should work as normal, chest1 empties into the hopper, then feeds into chest2.

Scenario B: hopper is locked, chests aren't
would still run the same as before, since access to chests are "public"

Scenario C: both chests are locked, not hopper
hopper wouldn't take or empty, as it doesn't share access with the chests

Scenario D: everything is locked by PlayerZ
chest1 locked by PlayerZ/or has access and hopper locked by PlayerZ/or has access would allow for hopper to interact with chest1. since chest2 is also locked by PlayerZ/ or has access, items would flow into chest2

with the system as it is, players have to interact with each chest/hopper to allow for flow

**Comment by spnda** [comment]
- Scenario A: Already works as intended.
- Scenario B: Already works as intended.
    However, the bottom chest can also be locked in this case, because there's no protection against someone moving their items into a chest they cannot access. That's on them for loosing their items, but that could maybe be subject to change?
- Scenario C: Already works as intended.
- Scenario D: I would deem this an issue and wrong behavior, because the Redstone protection is only there to protect hoppers taking items out of chests that are not owned by the same player.

I'm going to fix Scenario D now as it's not working as intended and I'd like to hear what you think about the issue with Scenario B :D

**Comment by spnda** [comment]
I've committed a fix for Scenario D. If you have any suggestions towards the issue with Scenario B, please go ahead. Otherwise, I'll close this issue as fixed.

**Comment by CaszGamerMD** [comment]
the default is redstone protection on, which prevents the flow of a hopper, if a hopper isn't locked it doesnt flow

**Comment by spnda** [comment]
Yes that's how it's supposed to work. With the above change a unlocked hopper will be able to extract from a chest with hopper protection off. If the protection is on the hopper has to be locked to the same player as the chest.

I'm wondering if you think it's good to let a hopper from player A move items into chest from player B, essentially letting player As items just disappear.

**Comment by CaszGamerMD** [comment]
No I'm saying if nothing is locked, all unlocked, hoppers still don't work, to make a hopper work it HAS to be locked and HAS to have it's Redstone Protection off for it to move any item.


I agree with you that chest and hopper have to have locks match to move item.

**Comment by spnda** [comment]
Are you trying this on the latest commit build or in beta.2? For me on latest commit it works.

**Comment by CaszGamerMD** [comment]
I was using the one on spigot

**Comment by spnda** [comment]
Ah, then it has been fixed.

**Comment by spnda** [comment]
I'll close this issue and if you have any new suggestions when the beta releases, please go ahead and reopen this issue. Thanks
